groups:
- name: CPUUtilisation
  labels:
    team: devops
  rules:
  - alert: CPUUtilisationAlert
    expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])*100)) > 70
    for: 1m
    keep_firing_for: 5m
    labels:
      severity: critical
    annotations:
      summary: High CPUUtilisation