route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
    - smarthost: <'SMTP end-point'> #'smtp.gmail.com:587'
      auth_username: <'your-username'>
      auth_password: <'your-password'>
      from: <'your-from-email'>
      to: <'your-to-email'>
      headers:
          subject: 'Prometheus Mail Alerts'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']